### ISSUE TITLE
JOSS Review Feedback (continued)

### ISSUE THREAD

**Issue by meghnathomas** [dbdespot/pysewer#2]
Hi @dbdespot! I am continuing my JOSS review here (originally started over on [Gitlab](https://git.ufz.de/despot/pysewer/-/issues/4)): 

Thank you for responding so quickly and thoroughly to my previous comments! 

- [x] I am now able to successfully install pysewer and run the `example_sewer_network` jupyter notebook file with (almost) no issues. My only remaining issue with installation is that the requirement "jupyterlab" is misspelled in the setup.py file.

- [x]  I would recommend adding text explaining you are demonstrating with the last few sections of code (Pump Optimization, Peak Flow Estimation, Selected Sewer Diameter, and Exporting Sewer Network). E.g., is pump location being optimized? What do the decision variables, constraints, and objective function look like? What inputs can the user change to customize the optimization problem? What is the specs of the pumps? What is a private pump vs a pumping station? I think the first few sections of this file are documented nicely and it would be very useful to document the rest the same way!

- [x] What is the `test_dataset` ipynb file for? Is it for you (the developers) to manually test pysewer functionality or is it for users to see pysewer applied to a different network? 

- [x] In the paper, you briefly allude to the fact that users can "contract the street network for more efficient graph traversal." Is this what the `simplify_graph` function is for? Is the` simplify_graph` function a function that users can utilize or is it only used behind the scenes? If users can use it, do you intend to show an application? If not, that's fine, but please specify in the docs/README that it exists as a function you offer

Docs and landing page README
- [x] Please update the docs with the updated installation instructions
- [x] I suggest adding a prominent link to the docs at the top of the README file 
- [x] Also add a link to the docs under the 'ABOUT' section on the top right of the github repository page for easy access
- [x] I suggest including a link to the `example_sewer_network` file both in your docs and in your landing page README file 

Paper
- [x] What are the contributions of the authors Mortiz Sanne, Ganbaatar Khurelbaatar, Manfred van Afferden, and Jan Friesen?
- [x] I recommend including references for Steiner tree and Djikstra's Shortest Path Algorithm.

Thanks!!

**Comment by ghost** [comment]
Hi @meghnathomas , thank you for the feedback and suggestions on improving the documentation. 

Below are the responses to the comments you made. 

### 1. Response to the installation of pysewer
Spelling check in `setup.py` is now completed.

### 2. Response to the extended explanation pysewer's functionality
We have elaborated on the hydraulic optimization process of pysewer directly in the example_network.ipynb and tried to answer some of the questions you listed in the comment above. Please note that we have changed the heading from Pump optimisation to Hydraulic design and optimisation, which gives a better overall description of that step in the analysis. Here you can find the [updated notebook](https://git.ufz.de/despot/pysewer/-/blob/main/notebooks/example_sewer_network.ipynb?ref_type=heads).

### 3. Response to the `test_dataset.ipynb` 
The `test_dataset.ipynb` file was mainly used to test the pysewer functionality and create smaller figures for the paper. We decided to keep this for the review process since the figures generated for the paper were made there. Furthermore, the unit tests were carried out using this dataset, and we thought including the workflow using the dataset in a dedicated notebook could be helpful. 

### 4.  Response to `simplify_graph function`
Yes, this is correct. Users can contract street networks for a more efficient graph traversal as part of the optimisation steps. The `simply_graph` is embedded in the `generate_connection_graph()` (the final preprocessing step), which transforms the initial graph into a fully functional and closed-to-optimized network ready for further design, analysis and optimisation. In principle, users can use the `simplify_graph` function in a similar way to the consolidate function of [osmnx](https://osmnx.readthedocs.io/en/stable/) or any other workflows used for simplifying the road network.  With this function, the main idea is to remove unnecessary nodes (intersections and dead-ends) and directly connect the endpoints that condense these nodes. Currently, users are limited to using this function for inspection and checking the simplification process. To do this, users can directly apply this function to the initial graph. We don’t intend to show this application but will add a note about its functionality.

Please note that the comments/tasks regarding the docs and landing readme page and the paper are done  directly in those parts and were made following the suggestions given.
[Link to the update docs](https://despot.pages.ufz.de/pysewer/)
[Link to the updated paper](https://git.ufz.de/despot/pysewer/-/blob/main/paper/paper.pdf?ref_type=heads)

**Comment by meghnathomas** [comment]
Hi @dbdespot, awesome! Thank you for addressing all of my comments and questions so carefully. You guys have built a great package!

I have three tiny final comments but besides that I am happy to recommend your paper for acceptance!

- [x] The links in your Contributing section on both Gitlab and Github appear to be broken. See picture below:

![image](https://github.com/dbdespot/pysewer/assets/74310847/579df38a-92ec-446d-942d-8b263733c151)

Would you be able to fix those? I think it would be better to point users towards Github instead of Gitlab to raise issues because it seems to be difficult to contribute to the project on Gitlab if you're not from UFZ.

- [x] Could you add a few sentences in your paper describing how this software compares to other commonly-used packages?

- [x] Can you change the journal name for the Djikstra's algorithm citation to the full journal name (Numerische Mathematik I think - please double check!)?

As soon as these comments are addressed I will close this issue and recommend your paper for acceptance on the main review thread.

**Comment by ghost** [comment]
Hi @meghnathomas thank you for your quick response and the good news. 

The links to issues are now fixed. You are right; it is better to point users to GitHub when creating issues. Issues will be managed using GitHub.

Regarding the paper, we have updated the reference and added a few lines on how pysewer compares to other commonly used packages. You can find the updated changes [here](https://github.com/dbdespot/pysewer/tree/main/paper.)

On behalf of the authors involved, I would like to thank you for your review and the very useful comments and suggestions made during the review process.

**Comment by meghnathomas** [comment]
Great! Final note: I appreciate you citing the Thomas et al paper in your manuscript but that paper deals only with visualizing water networks and not generating new network models using graph theory! :-) I recommend replacing it with [this paper by Momeni et al](https://ascelibrary.org/doi/full/10.1061/JPSEA2.PSENG-1358) or another similar one! 

Besides that, I thank you all for your hard work and I hope the rest of the review process goes smoothly!
